//@version=6
indicator("Sulex Alpha", overlay=true, max_boxes_count=500, max_labels_count=500, max_lines_count=500)

//==================================================
// SULEX ALPHA
// Version : 0.1.0
// Author  : Sulex180
//==================================================

//========== INPUTS ==========
emaFast = input.int(20, "Fast EMA")
emaSlow = input.int(50, "Slow EMA")

showEMA = input.bool(true, "Show EMA")

//========== TREND ==========
fastEMA = ta.ema(close, emaFast)
slowEMA = ta.ema(close, emaSlow)

bullTrend = fastEMA > slowEMA
bearTrend = fastEMA < slowEMA

plot(showEMA ? fastEMA : na, title="Fast EMA", linewidth=2)
plot(showEMA ? slowEMA : na, title="Slow EMA", linewidth=2)

bgcolor(bullTrend ? color.new(color.green,90) : bearTrend ? color.new(color.red,90) : na)

//========== ALERTS ==========
alertcondition(bullTrend, title="Bull Trend", message="Bullish Trend Detected")
alertcondition(bearTrend, title="Bear Trend", message="Bearish Trend Detected")
